
python doAll.py --monolep --start=0 --stop=1
python doAll.py --monolep --start=1 --stop=2
python doAll.py --monolep --start=2 --stop=3
python doAll.py --monolep --start=3 --stop=4
python doAll.py --monolep --start=4 --stop=5
python doAll.py --monolep --start=5 --stop=6
python doAll.py --monolep --start=6 --stop=7
python doAll.py --monolep --start=7 --stop=8
python doAll.py --monolep --start=8 --stop=9
python doAll.py --monolep --start=9 --stop=10
python doAll.py --monolep --start=10 --stop=11
python doAll.py --monolep --start=11 --stop=12
python doAll.py --monolep --start=12 --stop=13
python doAll.py --monolep --start=13 --stop=14
python doAll.py --monolep --start=14 --stop=15
python doAll.py --monolep --start=15 --stop=16
python doAll.py --monolep --start=16 --stop=17
python doAll.py --monolep --start=17 --stop=18
python doAll.py --monolep --start=18 --stop=19
python doAll.py --monolep --start=19 --stop=20
