#ifndef SSPAIRS_H
#define SSPAIRS_H

class SSpairsTree {

    /**
     * TTree automatically generated by mktree
     */
    
    /* Initialize branches */
    TBranch* b_event;
    TBranch* b_run;
    TBranch* b_lumi;
    TBranch* b_TotalEvents;
    TBranch* b_MinPt;
    TBranch* b_Loose;
    TBranch* b_FO;
    TBranch* b_Tight;
    TBranch* b_SSpairs;
    TBranch* b_NoExtraZ;
    TBranch* b_Min2Jets;
    TBranch* b_Nobtags;
    TBranch* b_JetMass120;
    TBranch* b_JetMass500;
    TBranch* b_Min3Jets;
    TBranch* b_Min4Jets;

    public:

        // TTree and TFile
        TTree* t;
        TFile* tfile;

        /* Initialize branch values */
        int event;
        int run;
        int lumi;
        int TotalEvents;
        int MinPt;
        int Loose;
        int FO;
        int Tight;
        int SSpairs;
        int NoExtraZ;
        int Min2Jets;
        int Nobtags;
        int JetMass120;
        int JetMass500;
        int Min3Jets;
        int Min4Jets;


        /* Initialize other values */
        // -> Your values here <-

        /* Methods */
        // Constructor
        SSpairsTree(int year_int);
        // Reset variables
        void resetBranches();
        // Fillers
        int fillBranches();
        // Other
        void fillTTree();
        void writeTFile();
        // -> Your methods here <-
};

#endif
    
