#ifndef LEPTONS_H
#define LEPTONS_H

class LeptonsTree {

    /**
     * TTree automatically generated by mktree
     */
    
    /* Initialize branches */
    TBranch* b_lepton_pt;
    TBranch* b_lepton_eta;
    TBranch* b_lepton_phi;
    TBranch* b_event;
    TBranch* b_lepton_id;

    public:

        // TTree
        TTree *t;
        // Target file
        TFile* f;

        /* Initialize branch values */
        float lepton_pt;
        float lepton_eta;
        float lepton_phi;
        int event;
        int lepton_id;
        // Other
        int year;

        /* Methods */
        // Constructor
        LeptonsTree(int year);
        // Reset variables
        void reset();
        // Fillers
        int fillBranches();
        // Other
        /* Your methods here */
};

#endif
    
