#ifndef CMS4HYPS_H
#define CMS4HYPS_H

class CMS4HypsTree {

    /**
     * TTree automatically generated by mktree
     */
    
    /* Initialize branches */
    TBranch* b_leader_eta;
    TBranch* b_lagger_isTriggerSafe;
    TBranch* b_leader_isTriggerSafe;
    TBranch* b_lagger_id;
    TBranch* b_leader_id;
    TBranch* b_lagger_idx;
    TBranch* b_leader_idx;
    TBranch* b_leader_is_loose;
    TBranch* b_lagger_is_loose;
    TBranch* b_leader_is_tight;
    TBranch* b_lagger_is_tight;
    TBranch* b_lagger_eta;
    TBranch* b_hyp_class;
    TBranch* b_leader_pt;
    TBranch* b_lagger_pt;
    TBranch* b_is_dilepton_event;
    TBranch* b_event;
    TBranch* b_run;
    TBranch* b_lumi;

    public:

        // TTree
        TTree *t;

        /* Initialize branch values */
        float leader_eta;
        bool lagger_isTriggerSafe;
        bool leader_isTriggerSafe;
        int lagger_id;
        int leader_id;
        unsigned int lagger_idx;
        unsigned int leader_idx;
        bool leader_is_loose;
        bool lagger_is_loose;
        bool leader_is_tight;
        bool lagger_is_tight;
        float lagger_eta;
        int hyp_class;
        float leader_pt;
        float lagger_pt;
        bool is_dilepton_event;
        int event;
        int run;
        float lumi;

        /* Methods */
        // Constructor
        CMS4HypsTree();
        // Reset variables
        void reset();
        // Fillers
        int fillBranches();
        // Other
        /* Your methods here */
};

#endif
    
