#ifndef HYP_H
#define HYP_H

class HypTree {

    /**
     * TTree automatically generated by mktree
     */
    
    /* Initialize branches */
    TBranch* b_is_dilepton_event;
    TBranch* b_event;
    TBranch* b_hyp_class;
    TBranch* b_tight_pt;
    TBranch* b_loose_pt;

    public:

        // TTree
        TTree *t;

        /* Initialize branch values */
        bool is_dilepton_event;
        int event;
        int hyp_class;
        float tight_pt;
        float loose_pt;
        // Other
        int year;

        /* Methods */
        // Constructor
        HypTree(int year_init);
        // Reset variables
        void reset();
        // Fillers
        int fillBranches();
        // Other
        /* Your methods here */
};

#endif
